### PR TITLE
League stats

### PR DESCRIPTION
**Pull request by zacisaacson**
please help me merge this correctly

### CODE REVIEW

**Comment by zacisaacson** [comment]
All of the conflicts have been resolved. All they were is what was on the master that we changed in this branch today during group work. Please take a look at this and approve it before we merge to master. thanks guys!!! @sasloan @mcat56 @freeheeling

**Review by ghost — APPROVED** [review]
I was there for most of this so it all makes sense to me. it is all pretty and clean I am good with it

**Review by mcat56 — APPROVED** [review]
Needs refactoring and tests for helper methods. After that should be good!

**Review by freeheeling — APPROVED** [review]
Top notch, team!

**Pull request merged**
